services:
 sos-api:
    build:
      context: ../
      dockerfile: ./sos-api/Dockerfile
    container_name: sos-api
    ports:
      - "${API_PORT}:${API_PORT}"
      - "9440:9440" 
      - "3535:3535"
    networks:
      - sos-api
      - sos-db
    depends_on:
      - sos-db
      - redis
    restart: unless-stopped
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}
      REDIS_HOST: 'redis'
      REDIS_PORT: ${REDIS_PORT}
    volumes:
        - ../sos-api/:/sos-api
        - ../sos-api/config:/sos-api/config
        - /Users/Fuzail/Documents/Node-Typescript-Postgres/sos-api/node_modules
  
 redis:
    image: redis
    container_name: sos-redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT} - "6379:6379"
    networks:
      - sos-api
    volumes:
      - ./data-redis:/data

networks:
 sos-api:
    driver: bridge

volumes:
  data-redis: