version: '3.8'
services:
  sos-db:
    image: postgres:17
    container_name: sos-db
    restart: always
    networks:
        - sos-db
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./data-postgres:/var/lib/postgresql/data/
volumes:
  db:
    driver: local

networks:
  sos-db:
    driver: bridge
